package com.study.common;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

import com.study.bo.CaseStudyBO;
import com.study.model.CaseStudy;

public class TestCaseStudy {

	public static void main(String[] args) {

		ApplicationContext appContext = new ClassPathXmlApplicationContext("spring/config/BeanLocations.xml");
		
		CaseStudyBO caseStudyBo = (CaseStudyBO)appContext.getBean("caseStudyBo");
		
		/** Insert */
		
		CaseStudy caseStudy = new CaseStudy();
		caseStudy.setPatientId(Integer.valueOf(123));
		caseStudy.setPatientName("Neeraj");
		caseStudy.setStudyId("1.1.2");
		//caseStudy.setUniqueID(null); // AutoGenerated.  studyId
		caseStudyBo.save(caseStudy);
		
		/** select  **/
		CaseStudy study = caseStudyBo.findByCaseStudyId("1.1.2");
		System.out.println("Fetch Date :->\n "+study);
		
		/** Update **/
		study.setPatientName("Google");
		caseStudyBo.update(study);
		
		/** Delete **/
		caseStudyBo.delete(study);
		
		System.out.println("Done !!!");
		
	}

}
